import type { GroupColor, GroupRule, IgnoredSite, MatchScope, PortableData, Settings } from "./shared.js";

type OptionsState = { user: { id: string; email?: string } | null; settings: Settings; rules: GroupRule[]; ignoredSites: IgnoredSite[]; status: { authenticated: boolean; cloudSyncEnabled: boolean; syncRulesEnabled: boolean; syncIgnoreListEnabled: boolean; lastSuccessfulSyncAt: string | null; sync: { state: "ready" | "error"; message?: string } } };
type ImportPreview = { groupRuleCount: number; ignoredSiteCount: number };
const colors: readonly GroupColor[] = ["grey", "blue", "red", "yellow", "green", "pink", "purple", "cyan", "orange"];
const colorLabels: Record<GroupColor, string> = { grey: "灰色", blue: "蓝色", red: "红色", yellow: "黄色", green: "绿色", pink: "粉色", purple: "紫色", cyan: "青色", orange: "橙色" };
const $ = <T extends Element>(selector: string): T => { const item = document.querySelector<T>(selector); if (!item) throw new Error(`Missing element: ${selector}`); return item; };
const status = $("#status"), accountCard = $<HTMLElement>("#account-card"), loginRequired = $<HTMLElement>("#login-required"), loginInstruction = $<HTMLElement>("#login-instruction"), openLogin = $<HTMLButtonElement>("#open-login"), accountEmail = $("#account-email"), accountState = $("#account-state"), defaultColor = $<HTMLSelectElement>("#default-color"), cloudSync = $<HTMLInputElement>("#cloud-sync"), rulesSync = $<HTMLInputElement>("#rules-sync"), ignoreSync = $<HTMLInputElement>("#ignore-sync"), ruleForm = $<HTMLFormElement>("#rule-form"), ruleId = $<HTMLInputElement>("#rule-id"), ruleTitle = $<HTMLInputElement>("#rule-title"), ruleDomains = $<HTMLInputElement>("#rule-domains"), ruleScope = $<HTMLSelectElement>("#rule-scope"), ruleColor = $<HTMLSelectElement>("#rule-color"), ruleEnabled = $<HTMLInputElement>("#rule-enabled"), rulesList = $("#rules-list"), ignoredForm = $<HTMLFormElement>("#ignored-form"), ignoredDomain = $<HTMLInputElement>("#ignored-domain"), ignoredScope = $<HTMLSelectElement>("#ignored-scope"), ignoredList = $("#ignored-list"), importFile = $<HTMLInputElement>("#import-file"), importPreview = $("#import-preview"), confirmImport = $<HTMLButtonElement>("#confirm-import"), cancelImport = $<HTMLButtonElement>("#cancel-import");
let state: OptionsState | null = null;
let importReady = false;
async function send<T>(message: unknown): Promise<T> { const result = await chrome.runtime.sendMessage(message) as T & { error?: string }; if (result.error) throw new Error(result.error); return result; }
function showStatus(message: string, error = false): void { status.textContent = message; status.className = error ? "status error" : "status"; }
function populateColors(select: HTMLSelectElement): void { select.replaceChildren(); for (const color of colors) { const option = document.createElement("option"); option.value = color; option.textContent = colorLabels[color]; select.append(option); } }
function formatScope(scope: MatchScope): string { return scope === "exact" ? "仅精确域名" : "域名及其子域名"; }
function emptyList(message: string): HTMLParagraphElement { const item = document.createElement("p"); item.className = "empty"; item.textContent = message; return item; }
function renderRules(rules: GroupRule[]): void { rulesList.replaceChildren(); if (!rules.length) { rulesList.append(emptyList("还没有分组规则。")); return; } for (const rule of rules) { const row = document.createElement("article"); row.className = "list-item"; const detail = document.createElement("div"); const title = document.createElement("strong"); title.textContent = rule.title; const info = document.createElement("p"); info.className = "muted"; info.textContent = `${rule.domains.join("、")} · ${formatScope(rule.matchScope)} · ${colorLabels[rule.color]}${rule.enabled ? "" : " · 已停用"}`; detail.append(title, info); const actions = document.createElement("div"); actions.className = "list-actions"; const edit = document.createElement("button"); edit.type = "button"; edit.textContent = "编辑"; edit.addEventListener("click", () => editRule(rule)); const remove = document.createElement("button"); remove.type = "button"; remove.className = "secondary"; remove.textContent = "删除"; remove.addEventListener("click", () => void removeRule(rule.id)); actions.append(edit, remove); row.append(detail, actions); rulesList.append(row); } }
function renderIgnored(sites: IgnoredSite[]): void { ignoredList.replaceChildren(); if (!sites.length) { ignoredList.append(emptyList("还没有忽略的网站。")); return; } for (const site of sites) { const row = document.createElement("article"); row.className = "list-item"; const detail = document.createElement("div"); const domain = document.createElement("strong"); domain.textContent = site.domain; const info = document.createElement("p"); info.className = "muted"; info.textContent = formatScope(site.matchScope); detail.append(domain, info); const remove = document.createElement("button"); remove.type = "button"; remove.className = "secondary"; remove.textContent = "删除"; remove.addEventListener("click", () => void removeIgnored(site.id)); row.append(detail, remove); ignoredList.append(row); } }
function setAuthenticatedUi(authenticated: boolean): void { accountCard.hidden = !authenticated; loginRequired.hidden = authenticated; document.querySelectorAll<HTMLButtonElement>(".nav-link").forEach((button) => { const available = authenticated || button.dataset.panel === "account"; button.disabled = !available; button.setAttribute("aria-disabled", String(!available)); }); if (!authenticated) { document.querySelectorAll<HTMLElement>(".panel").forEach((panel) => { panel.hidden = panel.id !== "account"; }); document.querySelectorAll<HTMLButtonElement>(".nav-link").forEach((button) => { const active = button.dataset.panel === "account"; button.classList.toggle("active", active); button.setAttribute("aria-current", active ? "page" : "false"); }); } }
function render(next: OptionsState): void { state = next; const authenticated = next.status.authenticated; setAuthenticatedUi(authenticated); accountEmail.textContent = next.user?.email ?? "未登录"; accountState.textContent = authenticated ? `云端同步${next.status.cloudSyncEnabled ? "已启用" : "已关闭"}${next.status.lastSuccessfulSyncAt ? `，上次成功：${new Date(next.status.lastSuccessfulSyncAt).toLocaleString("zh-CN")}` : ""}${next.status.sync.state === "error" ? `，${next.status.sync.message}` : ""}` : "请先通过扩展弹窗登录。"; if (!authenticated) return; defaultColor.value = next.settings.defaultGroupColor ?? "blue"; cloudSync.checked = next.settings.cloudSyncEnabled ?? true; rulesSync.checked = next.settings.syncRulesEnabled ?? true; ignoreSync.checked = next.settings.syncIgnoreListEnabled ?? true; renderRules(next.rules); renderIgnored(next.ignoredSites); }
async function load(): Promise<void> { render(await send<OptionsState>({ type: "get-options-state" })); }
function settingsPayload(): Settings { if (!state) throw new Error("设置尚未加载"); return { ...state.settings, defaultGroupColor: defaultColor.value as GroupColor, cloudSyncEnabled: cloudSync.checked, syncRulesEnabled: rulesSync.checked, syncIgnoreListEnabled: ignoreSync.checked, lastSuccessfulSyncAt: null }; }
function resetRuleForm(): void { ruleForm.reset(); ruleId.value = ""; ruleEnabled.checked = true; $("#rule-submit").textContent = "添加规则"; $<HTMLButtonElement>("#rule-cancel").hidden = true; }
function editRule(rule: GroupRule): void { ruleId.value = rule.id; ruleTitle.value = rule.title; ruleDomains.value = rule.domains.join(", "); ruleScope.value = rule.matchScope; ruleColor.value = rule.color; ruleEnabled.checked = rule.enabled; $("#rule-submit").textContent = "保存规则"; $<HTMLButtonElement>("#rule-cancel").hidden = false; document.querySelector<HTMLElement>("#rule-form")?.scrollIntoView({ behavior: "smooth", block: "center" }); ruleTitle.focus(); }
async function removeRule(id: string): Promise<void> { if (!window.confirm("确定要删除这条分组规则吗？")) return; try { await send({ type: "delete-group-rule", id }); await load(); showStatus("分组规则已删除"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } }
async function removeIgnored(id: string): Promise<void> { if (!window.confirm("确定要删除这个忽略网站吗？")) return; try { await send({ type: "delete-ignored-site", id }); await load(); showStatus("忽略网站已删除"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } }
for (const select of [defaultColor, ruleColor]) populateColors(select);
document.querySelectorAll<HTMLButtonElement>(".nav-link").forEach((button) => button.addEventListener("click", () => { const target = button.dataset.panel; if (!target) return; document.querySelectorAll<HTMLElement>(".panel").forEach((panel) => { panel.hidden = panel.id !== target; }); document.querySelectorAll<HTMLButtonElement>(".nav-link").forEach((item) => { const active = item === button; item.classList.toggle("active", active); item.setAttribute("aria-current", active ? "page" : "false"); }); $<HTMLElement>("#" + target).focus(); }));
openLogin.addEventListener("click", () => void (async () => { loginInstruction.hidden = true; try { await chrome.action.openPopup(); } catch { loginInstruction.hidden = false; showStatus("请从浏览器工具栏打开 Tab Garden 弹窗并登录。", true); } })());
$("#settings-form").addEventListener("submit", (event) => { event.preventDefault(); void (async () => { try { await send({ type: "save-options-settings", settings: settingsPayload() }); await load(); showStatus("设置已保存"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } })(); });
$("#appearance-form").addEventListener("submit", (event) => { event.preventDefault(); void (async () => { try { await send({ type: "save-options-settings", settings: settingsPayload() }); await load(); showStatus("默认颜色已保存"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } })(); });
$("#sync-now").addEventListener("click", () => void (async () => { try { const result = await send<{ synced: boolean }>({ type: "sync-now" }); await load(); showStatus(result.synced ? "同步完成" : "云端同步未启用或尚未登录"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } })());
$("#sign-out").addEventListener("click", () => void (async () => { try { await send({ type: "auth-sign-out" }); await load(); showStatus("已退出登录"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } })());
ruleForm.addEventListener("submit", (event) => { event.preventDefault(); void (async () => { const rule = { id: ruleId.value, title: ruleTitle.value, domains: ruleDomains.value.split(/[,\n]/).map((item) => item.trim()).filter(Boolean), matchScope: ruleScope.value, color: ruleColor.value, enabled: ruleEnabled.checked }; try { await send({ type: ruleId.value ? "update-group-rule" : "create-group-rule", rule }); resetRuleForm(); await load(); showStatus("分组规则已保存"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } })(); });
$("#rule-cancel").addEventListener("click", resetRuleForm);
ignoredForm.addEventListener("submit", (event) => { event.preventDefault(); void (async () => { try { await send({ type: "create-ignored-site", site: { domain: ignoredDomain.value, matchScope: ignoredScope.value } }); ignoredForm.reset(); await load(); showStatus("忽略网站已添加"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } })(); });
$("#export-data").addEventListener("click", () => void (async () => { try { const { data } = await send<{ data: PortableData }>({ type: "export-options-data" }); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "tab-garden-settings.json"; anchor.hidden = true; document.body.append(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); showStatus("数据已导出"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } })());
importFile.addEventListener("change", () => void (async () => { const file = importFile.files?.[0]; importReady = false; confirmImport.disabled = true; cancelImport.disabled = true; importPreview.textContent = ""; if (!file) return; try { const preview = await send<ImportPreview>({ type: "import-options-data", data: await file.text() }); importReady = true; confirmImport.disabled = false; cancelImport.disabled = false; importPreview.textContent = `将导入 ${preview.groupRuleCount} 条分组规则和 ${preview.ignoredSiteCount} 个忽略网站。`; } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } })());
confirmImport.addEventListener("click", () => void (async () => { if (!importReady || !window.confirm("确认导入并覆盖当前设置、分组规则和忽略网站吗？")) return; try { await send({ type: "import-options-data", confirmed: true }); importReady = false; importFile.value = ""; importPreview.textContent = "导入完成。"; confirmImport.disabled = true; cancelImport.disabled = true; await load(); showStatus("设置已导入"); } catch (error) { showStatus(error instanceof Error ? error.message : String(error), true); } })());
cancelImport.addEventListener("click", () => void (async () => { await send({ type: "import-options-data", cancelled: true }); importReady = false; importFile.value = ""; importPreview.textContent = "已取消导入。"; confirmImport.disabled = true; cancelImport.disabled = true; })());
void load().catch((error) => showStatus(error instanceof Error ? error.message : String(error), true));
